version: '3'
services:
  web:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgresql://postgres@postgres/casting
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: casting
      POSTGRES_HOST_AUTH_METHOD: trust